{"name": "Логин с неверными учетными данными", "status": "passed", "parameters": [{"name": "test_cases_input", "value": "{'email': 'test@example.com', 'password': ''}"}], "start": 1741824936190, "stop": 1741824936298, "uuid": "d7cc5ee1-d591-4fc5-af8d-de022685e545", "historyId": "1f233a7137ebb682a2e312aa3e7022f0", "testCaseId": "cf44ea55174a74afa9efcb95a068cfd0", "fullName": "tests.test_login_user.TestLogin#test_login_invalid_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "TerekhovHONOR"}, {"name": "thread", "value": "18088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}